paths:
  static: ''
  uploads: include/assets/uploads
timezone: Europe/Madrid
markdown:
  engine: kramdown
  options:
    heading_ids: false
    gfm: false
    breaks: false
    typographer: false
    attributes: true
    attribute_elements:
      inline: right
      block: below
      tr: none
      td: none
      li: right-of-prefix
    treat_indentation_as_code: true
_snippets_imports:
  jekyll: true
collections_config:
  pages:
    path: ''
    icon: wysiwyg
  drafts:
    path: _drafts
    icon: event
    create:
      publish_to: posts
    _inputs:
      categories:
        type: multiselect
        options:
          values: collections.posts[*].categories
          allow_create: true
      tags:
        type: multiselect
        options:
          values: collections.posts[*].tags
          allow_create: true
  posts:
    path: _posts
    icon: event_available
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    _inputs:
      categories:
        type: multiselect
        options:
          values: collections.posts[*].categories
          allow_create: true
      tags:
        type: multiselect
        options:
          values: collections.posts[*].tags
          allow_create: true
    add_options:
      - name: Add Post
      - name: Add Draft
        collection: drafts
  ramas:
    path: _ramas
    icon: radar
